extends:
  - ./reports/queries.json5
  - ./reports/default.json5
  - ./reports/screaming_frog.json5

offloadBodyHtml: 'db'

spider:
  seed:
   - https://www.example.com
  saveCookies: true
  savePerformance: true
  saveXhrList: true
  urls:
    crawl: "http*://{*.}example.com/{*,*/**}"

analysis:
  # SF actually EXCLUDES portions of the page by default rather than
  # using a positive selector. We can simulate that using our regions
  # feature, but it's not automatic yet.
  content:
    selector: main 

  properties:

    # Screaming Frog's default report shows the first two H1 and H2 tags;
    # we'll pull them out for reporting purposes.
    content.h1:
      source: body
      selector: "h1"
      limit: 2
    content.h2:
      source: body
      selector: "h2"
      limit: 2

    content.cms:
      - "tech.CMS.[0]"
      - "tech.Blogs.[0]"
      - "tech.Page Builders.[0]"
      - "tech.Message Boards.[0]"
    content.title:
      - 'data.meta.og.title'                   # OpenGraph
      - 'data.title'                           # HEAD title tag
    content.description:
      - 'data.meta.og.description'             # OpenGraph
      - 'data.schemaOrg.WebPage.description'   # Schema.org description
      - 'data.meta.description'                # HEAD meta description
    content.date:
      - 'data.meta.datePublished'              # Sometimes-used meta tag
      - 'data.meta.og.article.published_time'  # Opengraph publish timestamp
      - 'data.schemaOrg.WebPage.datePublished' # Schema.org web page publish date